import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// Generated by docusaurus-plugin-openapi-docs from the OpenAPI spec
// shipped in @atomicmemory/atomicmemory-core. Regenerated on every
// prestart / prebuild so the HTTP API sidebar tracks core releases.
import httpApiSidebar from './docs/api-reference/http/sidebar';

const sidebars: SidebarsConfig = {
  // Platform concepts — the "why modular" story
  platformSidebar: [
    'introduction',
    'quickstart',
    {
      type: 'category',
      label: 'Platform',
      collapsed: false,
      items: [
        'platform/architecture',
        'platform/composition',
        'platform/consuming-core',
        'platform/stores',
        'platform/providers',
        'platform/scope',
        'platform/observability',
      ],
    },
  ],

  // SDK — the TypeScript client, pluggable across memory backends
  sdkSidebar: [
    'sdk/overview',
    'sdk/quickstart',
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'sdk/concepts/architecture',
        'sdk/concepts/provider-model',
        'sdk/concepts/capabilities',
        'sdk/concepts/scopes-and-identity',
        'sdk/concepts/storage-adapters',
        'sdk/concepts/embeddings',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'sdk/guides/atomicmemory-backend',
        'sdk/guides/mem0-backend',
        'sdk/guides/custom-provider',
        'sdk/guides/browser-helpers',
        'sdk/guides/nodejs-server',
        'sdk/guides/browser-primitives',
        'sdk/guides/swapping-backends',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [
        'sdk/api/overview',
        'sdk/api/memory-provider',
        'sdk/api/errors',
      ],
    },
  ],

  // Integrations — coding agents (Claude Code, OpenClaw, Codex, Cursor)
  // and AI frameworks (Vercel AI SDK, LangChain JS, Mastra, …) that
  // consume AtomicMemory through the shared MCP server + per-tool
  // plugin wrappers shipped from Atomicmemory-integrations.
  integrationsSidebar: [
    'integrations/overview',
    {
      type: 'category',
      label: 'Coding Agents',
      collapsed: false,
      items: [
        'integrations/coding-agents/claude-code',
        'integrations/coding-agents/openclaw',
        'integrations/coding-agents/codex',
        'integrations/coding-agents/cursor',
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      collapsed: false,
      items: [
        'integrations/frameworks/vercel-ai-sdk',
        'integrations/frameworks/langchain-js',
        'integrations/frameworks/mastra',
        'integrations/frameworks/openai-agents',
        'integrations/frameworks/langgraph-js',
      ],
    },
  ],

  // HTTP API reference — generated from @atomicmemory/atomicmemory-core's
  // OpenAPI spec by docusaurus-plugin-openapi-docs. The `conventions`
  // intro page stays hand-maintained and anchors the section.
  apiReferenceSidebar: [
    'api-reference/http/conventions',
    {
      type: 'category',
      label: 'HTTP API',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'HTTP API Reference',
        description:
          'Generated from the OpenAPI spec shipped in @atomicmemory/atomicmemory-core.',
      },
      items: httpApiSidebar,
    },
  ],
};

export default sidebars;
